### ISSUE TITLE
Configurar o domínio e hospedagem na Vercel

### ISSUE THREAD

**Issue by rafaelleitedasilva** [rafaelleitedasilva/laravel-vite#2]

**Comment by MateusRSdev** [comment]
cara tenho visto esse seu repositorio e queria pedir sua ajuda estou tentando fazer o  laravel funcionar no vercel ja tem uns dias e até que consegui fazer ele funcionar com todas as funcoes mas o problema é que quando eu linko um arquivo qualquer na view seja css ou js ele nao carrega. pelo que parece o vercel bloqueia as requisicoes desses recursos vc poderia me dizer como caralhos fez isso  funcionar ja analizei todo o seu repo e ainda nao consegui descobrir

**Comment by rafaelleitedasilva** [comment]
Opa mano eu ajudo sim, o segredo está no arquivo app.js na pasta resources/js.

[cid:7afb4d90-97c6-4e77-93c1-a213c4be6a78]
É aqui que você importa todos os js/css e pastas com arquivos, quando a Vercel rodar o build do Vite tudo que estiver aqui vai ser importado para a pasta public e aí você poderá pegar usando o Vite Service, desse jeito:

[cid:b36aa4f6-dad1-4e71-9600-b5e4f581410c]

Para trazer os estilos e scripts dentro do app.js você vai precisar outra diretiva:
[cid:a00f7d82-1c9d-4829-a60d-cb32b96036fd]
Que vai ficar no head da sua aplicação:
[cid:6a392a92-4c39-4b77-bf59-7d45065f1ab3]

Não se esqueça de configurar o Vite.config também...
[cid:41d7a2c2-dc45-4daf-8e57-4bc7e50b105f]

Se você quiser eu posso fazer um pull request com as alterações...
________________________________
De: Mateus Ramos ***@***.***>
Enviado: terça-feira, 26 de setembro de 2023 02:25
Para: rafaelleitedasilva/laravel-vite ***@***.***>
Cc: Rafael ***@***.***>; State change ***@***.***>
Assunto: Re: [rafaelleitedasilva/laravel-vite] Configurar o domínio e hospedagem na Vercel (Issue #2)


cara tenho visto esse seu repositorio e queria pedir sua ajuda estou tentando fazer o laravel funcionar no vercel ja tem uns dias e até que consegui fazer ele funcionar com todas as funcoes mas o problema é que quando eu linko um arquivo qualquer na view seja css ou js ele nao carrega. pelo que parece o vercel bloqueia as requisicoes desses recursos vc poderia me dizer como caralhos fez isso funcionar ja analizei todo o seu repo e ainda nao consegui descobrir
